#!/usr/bin/perl
use strict;
use warnings;

my $gitRepo = "git://github.com/teleshoes/net.git";

sub run(@){
  print "@_\n";
  system @_;
}

my $host = `raspi`;
chomp $host;

my $wifiConf = "/etc/wifi.conf";
my $wifiAutoConf = "/etc/wifi-auto.conf";

run "scp", "$ENV{HOME}/wifi.conf","root\@$host:$wifiConf";
run "scp", "$ENV{HOME}/wifi-auto.conf", "root\@$host:$wifiAutoConf";

run "raspi", "-b", "
  if [ -e /opt/net ]; then
    echo updating net git repo
    cd /opt/net
    git pull
  else
    echo fetching net git repo
    cd /opt
    git clone $gitRepo
  fi
  echo running net install
  cd /opt/net
  ./install.pl

  echo removing driver line from $wifiConf
  sed -i s/^driver=.*// $wifiConf
";
