#!/usr/bin/perl
use strict;
use warnings;

my $depsDir = "$ENV{HOME}/Code/raspi/klomp";
my $gitRepo = "git://github.com/teleshoes/klomp.git";

sub run(@){
  print "@_\n";
  system @_;
}

run "scp $depsDir/.klomplib pi\@`raspi`:/home/pi";

run "raspi", "-b", "
  if [ -e /opt/klomp ]; then
    echo updating klomp git repo
    cd /opt/klomp
    git pull
  else
    echo fetching klomp git repo
    cd /opt
    git clone $gitRepo
  fi
  echo running klomp install
  cd /opt/klomp
  ./install.pl /usr
  echo installing dependencies for tagging/etc
  ./dependency-install.pl
";
