#!/usr/bin/perl
use strict;
use warnings;

sub runRemote(@);

my $IPMAGIC_NAME = "raspi";

my @PKG_REMOVALS = (
  "libtag1-rusxmms",
  "wolfram-engine",  #deps: libxcb-cursor0 pi-language-support
);

my $PKG_INSTALLS = {
  '1' => [qw(
    vim-gtk rsync wget git openvpn screen
  )],
  '2' => [qw(
    libterm-readkey-perl libtext-csv-perl libts0
  )],
  '3' => [qw(
    x11vnc lsof psmisc zip unzip parted
    fonts-droid-fallback fonts-vlgothic
    fonts-opensymbol fonts-liberation fonts-linuxlibertine
    fonts-sil-gentium fonts-sil-gentium-basic
    fonts-inconsolata
  )],
  '4' => [qw(
    xinit midori time streamer
  )],
  '5' => [qw(
    mplayer mpv man python-pip alsa-utils xdotool unclutter xscreensaver
  )],
  '6' => [qw(
    libcec4 libcec-dev
  )],
};

my $USAGE = "Usage:
  $0 -h|--help
    show this message

  $0 [all|packages|remove]
    install+remove configured packages
";

sub main(@){
  my $type = "all";
  while(@_ > 0){
    my $arg = shift;
    if($arg =~ /^(-h|--help)$/){
      print $USAGE;
      exit 0;
    }elsif($arg =~ /^(all|packages|remove)$/){
      $type = $arg;
    }else{
      die "$USAGE\nERROR: unknown arg $arg\n";
    }
  }

  if($type =~ /^(all|packages)$/){
    for my $pkgGroup(sort keys %$PKG_INSTALLS){
      my @packages = @{$$PKG_INSTALLS{$pkgGroup}};
      print "\n\nInstalling group[$pkgGroup]:\n----\n@packages\n----\n";
      runRemote ''
        . "yes |"
        . " apt-get install"
        . " -y --allow-unauthenticated"
        . " @packages";
    }
  }

  runRemote("apt remove @PKG_REMOVALS") if $type =~ /^(all|remove)/;
}

sub runRemote(@){
  my @cmd = ("ipmagic", $IPMAGIC_NAME, "-u", "root", @_);
  system @cmd;
  die "error running '@cmd'\n" if $? != 0;
}

&main(@ARGV);
