#!/usr/bin/perl
use strict;
use warnings;

my $IPMAGIC_NAME = "raspi";
my $gitRepo = "git://github.com/teleshoes/qtbigtext.git";
my $dir = "/tmp/qtbigtext";

sub run(@){
  print "@_\n";
  system @_;
}

run "ipmagic", $IPMAGIC_NAME, "-u", "root", "-b", "
  rm -rf $dir
  git clone $gitRepo $dir
  cd $dir
  ./install.pl
";
