#!/usr/bin/perl
use strict;
use warnings;

my $gitRepo = "git://github.com/teleshoes/net.git";

sub run(@){
  print "@_\n";
  system @_;
}

run "raspi", "-b", "
  if [ -e /opt/net ]; then
    echo updating net git repo
    cd /opt/net
    git pull
  else
    echo fetching net git repo
    cd /opt
    git clone $gitRepo
  fi
  echo running net install
  cd /opt/net
  ./install.pl
";
