#!/usr/bin/perl
use strict;
use warnings;

sub run(@);

my $IPMAGIC_NAME = "raspi";

my @pip = qw(
  rpi.gpio RPLCD
);

sub main(@){
  run "ipmagic", $IPMAGIC_NAME, "
    set -x
    apt-get install python-dev python-pip
    pip install --break-system-packages @pip
  ";
}

sub run(@){
  print "@_\n";
  system @_;
}

&main(@ARGV);
