#!/usr/bin/perl
use strict;
use warnings;

my $gitUrl = 'git@github.com:teleshoes/twip.git';
my $gitRepoDir = "/tmp/twip";
my $tmpTwipConfig = '/tmp/twip-config';
my $twipConfig = "$ENV{HOME}/.twip";
my $host = `raspi`;
chomp $host;

if(-d $gitRepoDir){
  system "cd $gitRepoDir; git pull";
}else{
  system "git clone $gitUrl $gitRepoDir";
}


system "rsync", "-avP", "--del", "$gitRepoDir/", "root\@$host:$gitRepoDir";

system "rsync", "-avP", $twipConfig, "root\@$host:$tmpTwipConfig";

system "raspi", "-s", ''
  . "set -x; "
  . "cp $tmpTwipConfig /root/.twip; "
  . "chown root.root /root/.twip; "
  . "cp $tmpTwipConfig /home/pi/.twip; "
  . "chmod go-rw /home/pi/.twip /root/.twip; "
  . "chown pi.pi /home/pi/.twip; "
  . "cd $gitRepoDir; "
  . "perl install.pl; "
;
