#!/usr/bin/perl
use strict;
use warnings;
use File::Basename qw(basename);

sub run(@);

my $EXEC = basename $0;

my $IPMAGIC_NAME="raspi";
my $USER="pi";

my $USAGE = "Usage:
  $EXEC -h|--help
    show this message
";

sub main(@){
  while(@_ > 0){
    my $arg = shift;
    if($arg =~ /^(-h|--help)$/){
      print $USAGE;
      exit 0;
    }else{
      die "ERROR: unknown arg $arg\n";
    }
  }

  my $host = `ipmagic $IPMAGIC_NAME`;
  chomp $host;

  print "setup sshc $USER\n";
  run "sshc", "--close", "$USER\@$host";
  run "sshc", "$USER\@$host", "echo ok $USER\n";

  print "set passwords and enable ssh root login\n";
  run "sshc", "$USER\@$host", "sudo su -c '
    set -x
    passwd $USER
    passwd root
    sed -i \"s/^\\s*#*\\s*PermitRootLogin\\s.*/PermitRootLogin yes/\" /etc/ssh/sshd_config;
    sed -i \"s/^\\s*#*\\s*GatewayPorts\\s.*/GatewayPorts yes/\" /etc/ssh/sshd_config;
    sed -i \"s/^\\s*#*\\s*UseDNS\\s.*/UseDNS no/\" /etc/ssh/sshd_config;

    systemctl restart sshd;
  '";

  print "sleep 3s\n";
  sleep 3;

  print "setup sshc root\n";
  run "sshc", "--close", "root\@$host";
  run "sshc", "root\@$host", "echo ok root";

  print "ssh-keygen\n";
  run "sshc", "$USER\@$host", "
    set -x
    if [ ! -f ~/.ssh/$host.pub ]; then
      ssh-keygen -f ~/.ssh/id_rsa -N '' -t rsa
      mv ~/.ssh/id_rsa.pub ~/.ssh/$host.pub
    fi
  ";

  print "create root ssh dir\n";
  run "sshc", "root\@$host", "
    set -x
    mkdir -p /root/.ssh/
  ";

  print "fetch pubkey\n";
  run "sshc", "--scp", "$USER\@$host:~/.ssh/$host.pub", "~/.ssh/$host.pub";

  print "run pubkeys\n";
  run "pubkeys", "$IPMAGIC_NAME", "scp";
  run "pubkeys", "$IPMAGIC_NAME-root", "scp";


  print "set perms on ssh config\n";
  run "ipmagic", "$IPMAGIC_NAME", "-u", "$USER", "touch", "/home/$USER/.ssh/config";
  run "ipmagic", "$IPMAGIC_NAME", "-u", "$USER", "chmod 655", "/home/$USER/.ssh/config";

  print "cleanup\n";
  run "sshc", "--close", "$USER\@$host";
  run "sshc", "--close", "root\@$host";
}

sub run(@){
  print "@_\n";
  system @_;
}

&main(@ARGV);
