#!/usr/bin/perl
use strict;
use warnings;
use lib "$ENV{HOME}/install/bin";
use ScriptScript;

sub editConfigContents($);
sub editCmdlineContents($);
sub editRemoteFile($$);

my $IPMAGIC_NAME = "raspi";

my $FW_CONFIG_FILE = "/boot/firmware/config.txt";
my $FW_CMDLINE_FILE = "/boot/firmware/cmdline.txt";

my $CMDLINE_VIDEO_NAME = "HDMI-A-1";
my $MARGIN_OVERSCAN_WIDTH = 225;
my $MARGIN_OVERSCAN_HEIGHT = 120;

sub main(@){
  editRemoteFile($FW_CONFIG_FILE, \&editConfigContents);
  editRemoteFile($FW_CMDLINE_FILE, \&editCmdlineContents);
}

sub editConfigContents($){
  my ($contents) = shift;
  return $contents;
}

sub editCmdlineContents($){
  my ($contents) = shift;

  $contents =~ s/[\r\n]+$//;
  if($contents =~ /\n/){
    die "ERROR: multi-line cmdline $contents\n";
  }

  #remove existing margins from end of cmdline for idempotency
  $contents =~ s/\s+video=$CMDLINE_VIDEO_NAME:(,?margin_(?:left|right|top|bottom)=\d+)*\s*$//;

  if($contents =~ /\bvideo=/){
    die "ERROR: unknown video= arg in cmdline\n$contents\n";
  }

  $contents .= " video=$CMDLINE_VIDEO_NAME:"
    . "margin_left=0,"
    . "margin_right=$MARGIN_OVERSCAN_WIDTH,"
    . "margin_top=0,"
    . "margin_bottom=$MARGIN_OVERSCAN_HEIGHT"
  ;

  $contents .= "\n";

  return $contents;
}

sub editRemoteFile($$){
  my ($remoteFile, $editSub) = @_;

  my $tmpFile = "/tmp/raspi-boot-tmp-file-" . nowMillis();
  run "ipmagic", $IPMAGIC_NAME, "-u", "root", "--scp",
    ":$remoteFile", "$tmpFile";

  if(editFile($tmpFile, $editSub)){
    run "ipmagic", $IPMAGIC_NAME, "-u", "root", "--scp",
      "$tmpFile", ":$remoteFile";

    print "\n\n===== UPDATED $remoteFile\n\n";
  }else{
    print "\n\n===== skipped $remoteFile\n\n";
  }

  run "rm", $tmpFile;
}

&main(@ARGV);
