#!/usr/bin/perl
use strict;
use warnings;
use File::Basename qw(basename);

sub run(@);
sub runIpmagic($@);

my $EXEC = basename $0;

my $IPMAGIC_NAME="raspi";
my $USER="pi";

my $USAGE = "Usage:
  $EXEC -h|--help
    show this message

  $EXEC [OPTS]
    setup ssh keys on host $IPMAGIC_NAME

  OPTS
    -p | --passwd
      run `passwd $USER && passwd root` during initial setup
";

sub main(@){
  my $isRunPasswd = 0;
  while(@_ > 0){
    my $arg = shift;
    if($arg =~ /^(-h|--help)$/){
      print $USAGE;
      exit 0;
    }elsif($arg =~ /^(-p|--passwd)$/){
      $isRunPasswd = 1;
    }else{
      die "ERROR: unknown arg $arg\n";
    }
  }

  my $host = `ipmagic $IPMAGIC_NAME`;
  chomp $host;

  print "setup sshc $USER\n";
  runIpmagic $USER, "--sshc-close";
  runIpmagic $USER, "echo ok $USER";

  my $passwdCmd = $isRunPasswd ? "passwd" : "echo skipping passwd";

  print "set passwords and enable ssh root login\n";
  runIpmagic $USER, "sudo su -c '
    set -x
    $passwdCmd $USER
    $passwdCmd root
    sed -i \"s/^\\s*#*\\s*PermitRootLogin\\s.*/PermitRootLogin yes/\" /etc/ssh/sshd_config;
    sed -i \"s/^\\s*#*\\s*GatewayPorts\\s.*/GatewayPorts yes/\" /etc/ssh/sshd_config;
    sed -i \"s/^\\s*#*\\s*UseDNS\\s.*/UseDNS no/\" /etc/ssh/sshd_config;

    systemctl restart sshd;
  '";

  print "sleep 3s\n";
  sleep 3;

  print "setup sshc root\n";
  runIpmagic "root", "--sshc-close";
  runIpmagic "root", "echo ok root";

  print "ssh-keygen\n";
  runIpmagic $USER, "
    set -x
    if [ ! -f ~/.ssh/$host.pub ]; then
      ssh-keygen -f ~/.ssh/id_rsa -N '' -t rsa
      mv ~/.ssh/id_rsa.pub ~/.ssh/$host.pub
    fi
  ";

  print "create root ssh dir\n";
  runIpmagic "root", "
    set -x
    mkdir -p /root/.ssh/
  ";

  print "fetch pubkey\n";
  runIpmagic $USER, "--scp", ":~/.ssh/$host.pub", "~/.ssh/$host.pub";

  print "run pubkeys\n";
  run "pubkeys", "$IPMAGIC_NAME", "scp";
  run "pubkeys", "$IPMAGIC_NAME-root", "scp";


  print "set perms on ssh config\n";
  runIpmagic $USER, "touch /home/$USER/.ssh/config";
  runIpmagic $USER, "chmod 655 /home/$USER/.ssh/config";

  print "cleanup\n";
  runIpmagic $USER, "--sshc-close";
  runIpmagic "root", "--sshc-close";
}

sub run(@){
  print "@_\n";
  system @_;
}

sub runIpmagic($@){
  my ($user, @args) = @_;
  run "ipmagic", "--sshc", $IPMAGIC_NAME, "-u", $user, @args;
}

&main(@ARGV);
